on:
  workflow_dispatch:

name: Update data

jobs:
    copy-files:
        runs-on: ubuntu-latest
        name: Copy Files

        steps:
          - name: Checkout Website repository
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
              path: ./hub_test_viz

          - name: Checkout Data repository
            uses: actions/checkout@v4
            with:
              repository: LucieContamin/hub_test_data
              fetch-depth: 0
              path: ./hub_test_data

          - name: Copy target data
            run: |
              cp -R ./hub_test_data/target_data/. ./hub_test_viz/target-data/

          - name: Setup R
            uses: r-lib/actions/setup-r@v2

          - name: Install system dependencies
            run: sudo apt-get install libcurl4-openssl-dev libudunits2-dev libgdal-dev

          - name: Install dependencies
            run: |
              R -e 'Sys.setenv("NOT_CRAN" = TRUE)
                    install.packages(c("arrow", "remotes", "dplyr"))
                    Sys.unsetenv("NOT_CRAN")
                    remotes::install_url("https://github.com/Infectious-Disease-Modeling-Hubs/hubData/archive/refs/heads/main.zip")'

          - name: Process model-output file
            run: |
              Rscript code/processing_code.R

          - name: Push Website repository
            run: |
              cd ./hub_test_viz
              git config user.name github-actions
              git config user.email "<>"
              if [ -n "$(git status --porcelain)" ]; then
                git add .
                git commit -m "Update data"
                git push
                  echo "Data updated";
              else
                echo "no updates";
              fi

